all: main test1 test2 test3 test4 priorityqueue_test
main: main.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall main.cc -o main
test1: test1.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall test1.cc -o test1
test2: test2.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall test2.cc -o test2
test3: test3.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall test3.cc -o test3
test4: test4.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall test4.cc -o test4
priorityqueue_test: priorityqueue_test.cc priorityqueue.hh
	c++ -std=c++11 -O2 -Wall priorityqueue_test.cc -o priorityqueue_test
